TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

DB_INSTALLS += $(SSCAN)/sscanApp/Db/standardScans.db

DB_INSTALLS += $(AUTOSAVE)/db/save_restoreStatus.db

DB_INSTALLS += $(IOCSTATS)/db/iocAdminSoft.db

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

