TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

DB_INSTALLS += $(ADCORE)/db/NDFileHDF5.template
DB_INSTALLS += $(ADCORE)/db/NDFileMagick.template
DB_INSTALLS += $(ADCORE)/db/NDROI.template
DB_INSTALLS += $(ADCORE)/db/NDROIStat.template
DB_INSTALLS += $(ADCORE)/db/NDROIStatN.template
DB_INSTALLS += $(ADCORE)/db/NDProcess.template
DB_INSTALLS += $(ADCORE)/db/NDStats.template
DB_INSTALLS += $(ADCORE)/db/NDTimeSeries.template
DB_INSTALLS += $(ADCORE)/db/NDTransform.template
DB_INSTALLS += $(ADCORE)/db/NDOverlay.template
DB_INSTALLS += $(ADCORE)/db/NDOverlayN.template
DB_INSTALLS += $(ADCORE)/db/NDColorConvert.template
DB_INSTALLS += $(ADCORE)/db/NDCodec.template
DB_INSTALLS += $(ADCORE)/db/NDPva.template

DB_INSTALLS += $(ADCORE)/db/ADBase.template
DB_INSTALLS += $(ADCORE)/db/NDArrayBase.template
DB_INSTALLS += $(ADCORE)/db/NDFile.template
DB_INSTALLS += $(ADCORE)/db/NDPluginBase.template
DB_INSTALLS += $(ADCORE)/db/NDStdArrays.template

DB_INSTALLS += $(ADSIMDETECTOR)/db/simDetector.template
DB_INSTALLS += $(ADURL)/db/URLDriver.template
DB_INSTALLS += $(ADPVADRIVER)/db/pvaDriver.template

DB_INSTALLS += $(SSCAN)/sscanApp/Db/standardScans.db

DB_INSTALLS += $(AUTOSAVE)/db/save_restoreStatus.db
DB += basic_asyn_motor.db
DB += motorSim.substitutions

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

